// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SpeedPort_Airlines.Data;

namespace Destination.Migrations
{
    [DbContext(typeof(SpeedPort_AirlinesContext)), Migration("20210727081339_CustomUserData")]
    internal abstract class CustomUserDataBase
    {
        protected abstract void BuildTargetModel(ModelBuilder modelBuilder);
    }
}