// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeedPort_Airlines.Data;

namespace SpeedPort_Airlines.Migrations.SpeedPort_AirlinesNew
{
    [DbContext(typeof(SpeedPort_AirlinesNewContext))]
    [Migration("20210728061207_createPromoTable")]
    partial class createPromoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpeedPort_Airlines.Models.Promo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PromoPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PromoValidity")
                        .HasColumnType("datetime2");

                    b.Property<string>("TravelAgency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Promo");
                });
#pragma warning restore 612, 618
        }
    }
}
